cedarcode/webauthn-ruby

lib/webauthn.rb
lib/webauthn/authenticator_attestation_response.rb
lib/webauthn/client_data.rb
spec/spec_helper.rb
spec/webauthn/authenticator_attestation_response_spec.rb
spec/webauthn_spec.rb

WebAuthn Recommendation reference:
https://w3c.github.io/webauthn/#base64url-encoding

fix: use separate encoding formats for comms with user-agent vs authenticators

---

README.md

Given the fact that Chrome 67 is now released, I updated the README.
I think this reads a little bit better :)

docs: update README with latest browser release notes

---

lib/webauthn/authenticator_assertion_response.rb
lib/webauthn/authenticator_attestation_response.rb
lib/webauthn/authenticator_data.rb
lib/webauthn/authenticator_response.rb

Hi! Thank you for working on WebAuthn RP helper library for Ruby. I'm maintaining https://github.com/sorah/clarion, which was implemented with legacy U2F API (u2f-api.js), and I have just replaced the legacy implementation of my app with this gem!
Current implementation hides many data available from authenticators behind the private methods. It is useful to expose them to users of this gem, i.e. logging, auditing, and debugging.
I believe this gem should provide a low-level API for RP implementations. Current implementation doesn't expose the most data available from authenticator, and have to implement reference at the entry points (`AuthenticatorAttestationResponse` and `AuthenticatorAssersionResponse`.)
AFAIK WebAuthn is designed to be extensible, so it's useless to force RP …

feat: Make methods public to expose data available

---

lib/webauthn/authenticator_assertion_response.rb
lib/webauthn/authenticator_attestation_response.rb
lib/webauthn/authenticator_response.rb
spec/webauthn/authenticator_assertion_response_spec.rb
spec/webauthn/authenticator_attestation_response_spec.rb

Closes https://github.com/cedarcode/webauthn-ruby/issues/72
RP ID may be different from request origin; i.e. client may override, or the appid extension may give legacy app id as a RP ID.
In most cases, rp_id can be expected to be a host part of request origin URI. So this patch allows `valid?` methods to take optional `rp_id`, then the methods handle the explicitly given one as a RP ID, instead of a host of origin URI, when it's given.
``` ruby
attestation.valid?(challenge, "https://a.example.com", rp_id: "example.com")
assertion.valid?(challenge, "https://a.example.com", rp_id: "https://a.example.com") # in case of +appid+ extension
```

feat: Accept rp_id explicitly on *Response#valid?

---

lib/webauthn/authenticator_data.rb
lib/webauthn/authenticator_response.rb
spec/support/fake_authenticator.rb
spec/webauthn/authenticator_assertion_response_spec.rb
spec/webauthn/authenticator_data_spec.rb

Follow up should be add some test coverage for this after https://github.com/cedarcode/webauthn-ruby/pull/70/files#diff-eda0ea1702d5d6e57c7f8eed6aa93151R24 is merged.

fix: make response valid if either UP or UV flags are present

---

lib/webauthn/attestation_statement.rb
lib/webauthn/attestation_statement/android_safetynet.rb
lib/webauthn/attestation_statement/base.rb
lib/webauthn/attestation_statement/fido_u2f.rb
lib/webauthn/attestation_statement/none.rb
lib/webauthn/attestation_statement/packed.rb
lib/webauthn/authenticator_attestation_response.rb
spec/webauthn/attestation_statement/packed_spec.rb
spec/webauthn/authenticator_attestation_response_spec.rb

The WebAuthn spec [notes](https://www.w3.org/TR/2018/CR-webauthn-20180807/#sctn-attestation-types) the following:
> Attestation statements conveying attestations of type AttCA use the same data structure as attestation statements conveying attestations of type Basic, so the two attestation types are, in general, distinguishable only with externally provided knowledge regarding the contents of the attestation certificates conveyed in the attestation
[Retrieving](https://fidoalliance.org/mds/) and managing the this external data ([TOC](https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-metadata-service-v2.0-id-20180227.html) and [statements](https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-metadata-statement-v2.0-id-20180227.html)) from the FIDO Metadata Service is up to the …

feat: expose attestation type and trust path after validation

---

webauthn.gemspec

For reasons we can't upgrade bundler yet at the moment where I work, and I don't believe anything is this gem actually requires 2.0. Loosening this requirement makes it just a bit easier to contribute in case other have a similar situation.

build: loosen bundler version requirement to allow 1.17 and 2.0

---

lib/webauthn.rb
lib/webauthn/authenticator_response.rb
lib/webauthn/security_utils.rb
spec/webauthn/security_utils_spec.rb

https://github.com/cedarcode/webauthn-ruby/commit/f1dc1c45846b1585aae75c131ebe4d347f81ceba adds a constant time comparision function called `secure_compare` to a `WebAuth::SecurityUtils` module. The code was adapted from https://github.com/rails/rails/blob/master/activesupport/lib/active_support/security_utils.rb.
https://github.com/cedarcode/webauthn-ruby/commit/f83f38b52e4ba29a3afaeb122fb01f474f59c0a5 replaces the `==` operator when comparing the challenge. `==` in Ruby is vulnerable to [timing attacks](https://www.slideshare.net/NickMalcolm/timing-attacks-and-ruby-on-rails). (Practical exploitation over the internet is very difficult, but better safe than sorry).
I would have ideally made `fixed_length_secure_compare` a private method but I guess you can't do that with modules?

Use constant time compare function for challenge comparison 

---

README.md
lib/webauthn/authenticator_assertion_response.rb
lib/webauthn/authenticator_attestation_response.rb
lib/webauthn/authenticator_data.rb
lib/webauthn/authenticator_response.rb
spec/webauthn/authenticator_assertion_response_spec.rb
spec/webauthn/authenticator_attestation_response_spec.rb

feat: add #verify method which raises meaningful errors

---

.travis.yml
README.md
spec/spec_helper.rb
spec/webauthn/authenticator_attestation_response_spec.rb

[libfaketime](https://github.com/wolfcw/libfaketime) allows us to stub time in OpenSSL. It is a bit harder to set up though, which is why I added some documentation and a hopefully helpful skip message.
On my macOS machine, everything succeeds by running:
`DYLD_INSERT_LIBRARIES=/usr/local/Cellar/libfaketime/2.9.7_1/lib/faketime/libfaketime.1.dylib DYLD_FORCE_FLAT_NAMESPACE=1 DONT_FAKE_MONOTONIC=1 FAKETIME_NO_CACHE=1 bundle exec rspec`
While a plain `bundle exec rspec` results in:
```
Pending: (Failures listed here are expected and do not affect your suite's status)
1) WebAuthn::AuthenticatorAttestationResponse when android-safetynet attestation verifies
Failure/Error: skip("libfaketime not preloaded? current time is #{current} expected #{new_time}") if current != new_time …
```

Fix Android SafetyNet tests that were failing due to time issues

---

README.md

Spent quite some time trying to replicate this functionality and stumbled upon the class when I was debugging responses with test authenticator data. Figure it would be good to call it out in the README.

Add documentation in the README about WebAuthn::FakeAuthenticator

---

spec/webauthn/authenticator_attestation_response_spec.rb

The W3C spec states at the end of every verification procedure for a attestation type:
> If successful, return implementation-specific values representing attestation type <x> and attestation trust path <y>
Thus the TODO comment makes no sense, we need to call `valid?` to make this data available

docs: remove TODO comments for attestation type and path

---

lib/webauthn/authenticator_data.rb
lib/webauthn/authenticator_data/attested_credential_data.rb
lib/webauthn/fake_authenticator.rb
spec/webauthn/authenticator_assertion_response_spec.rb
spec/webauthn/authenticator_data/attested_credential_data_spec.rb
webauthn.gemspec

Related to to #107 
~There's no fix yet. This is only a test change to reproduce/expose the issue.~

Don't fail when Extension Data is present

---

lib/webauthn/security_utils.rb

Hex encoding is base 16 which makes the original input twice as big. We don't need to encode the SHA256 output bytes and the shorter output means we spend less time in `SecureCompare.compare`
Same as https://github.com/rails/rails/pull/35556

Speed up secure compare

---

lib/webauthn/attestation_statement/fido_u2f.rb
lib/webauthn/attestation_statement/fido_u2f/public_key.rb
lib/webauthn/authenticator_assertion_response.rb
lib/webauthn/authenticator_data/attested_credential_data.rb
spec/spec_helper.rb
spec/webauthn/authenticator_assertion_response_spec.rb
spec/webauthn/authenticator_data/attested_credential_data_spec.rb

feat: generalize credential public key return value

---

lib/webauthn/attestation_statement/fido_u2f.rb
lib/webauthn/fake_authenticator.rb
lib/webauthn/fake_authenticator/authenticator_data.rb
spec/webauthn/attestation_statement/fido_u2f_spec.rb

The conformance test tool notified me of this (Server-ServerAuthenticatorAttestationResponse-Resp-8, test F-1). It used to be called out more clearly in the spec:
https://github.com/w3c/webauthn/pull/539/commits/4a376bf198f839abe123e5e32458c83d40b67f29 but that has been changed over time.
Now https://www.w3.org/TR/2019/PR-webauthn-20190117/#fido-u2f-attestation mentions only:
> Extract the claimed rpIdHash from authenticatorData, and the claimed credentialId and credentialPublicKey from authenticatorData.attestedCredentialData.
which is vague about what you're supposed to expect.
Fortunately we have https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-client-to-authenticator-protocol-v2.0-id-20180227.html#u2f-authenticatorMakeCredential-interoperability confirming the AAGUID should …

fix: verify U2F attested credential data AAGUID is zeroed out

---

lib/webauthn.rb

These fields are required by the spec, they have meaning in how and when they should be used: https://www.w3.org/TR/2019/PR-webauthn-20190117/#dictionary-pkcredentialentity
I think current the defaults are not helpful for users of the gem since they may be shown by the browser in the future. If this happens, the unchanged defaults may lead to authentication prompts like:
> Scan fingerprint to authenticate as web-user for web-server
To not break backwards compatibility while making the need for explicit configuration more obvious, I've made the keyword arguments optional for now with a note to change this for version 2.0.

refactor: make required credentials creation options more explicit

---

spec/conformance/Gemfile
spec/conformance/Gemfile.lock
spec/conformance/README.md
spec/conformance/server.rb

For use with the tool available https://fidoalliance.org/certification/functional-certification/conformance/ 
Kept dependancies as simple as possible on purpose. I've spoken to the FIDO Alliance certification director at an event and she mentioned they test open source implementations too at interop events, assuming they've self-certified using the tool. Once the gem is able I don't want them to have to fight with C-extension compilation 😅 
Still a bunch of things to refactor and fix inside the server code, I'll start opening issues for things that need fixing inside the gem as I work on this as time permits. Currently we're at 112 passes and 41 failures on tool version 0.10.211.

Add simple server to use with FIDO2 conformance test tool

---

lib/android_safetynet/attestation_response.rb
lib/webauthn/attestation_statement/android_safetynet.rb
spec/android_safetynet/attestation_response_spec.rb

refactor: draw an abstraction line between WebAuthn and AndroidSafetynet's AttestationResponse

---

README.md
lib/webauthn/authenticator_assertion_response.rb
lib/webauthn/authenticator_attestation_response.rb
lib/webauthn/authenticator_response.rb
spec/conformance/server.rb

Motivated by conversation in #150.
"original" is confusing here. It was intended to mean the original value when the ceremony started, but it might confuse by lead to think that during the Authentication ceremony, this is asking for the original value from the Registration, which is not what we want.
I considered naming them just `challenge` and `origin` , but I ended up with `expected_challenge` and `expected_origin`, because I was afraid that reading `response.verify(challenge, origin)` could lead to the potential confusion that this arguments are the ones being verified for correctness, when they are actually the expected values, and the things being verified are the ones "inside" the response.
However, not strong on that if someone else prefers shorter names.

refactor: make challenge/origin arguments less confusing

---

lib/webauthn.rb
spec/webauthn_spec.rb

Follow up from #163 
Addresses https://github.com/cedarcode/webauthn-ruby/commit/1514afbf07f140c5f7cf532bb0fc220db0545dcb#r33251669

feat: let RP accept RSA credentials as a second option by default

---

spec/webauthn/public_key_credential_spec.rb

E.g: 
> WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Actual error raised was #<RuntimeError: invalid type>. Instead consider providing a specific error class or message. This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`. Called from /Users/bdewater/src/github.com/bdewater/webauthn-ruby/spec/webauthn/public_key_credential_spec.rb:59:in `block (4 levels) in <top (required)>'.

Silence warnings about using 'raise_error' without providing a specific error

---

lib/cose/algorithm.rb
lib/webauthn/configuration.rb
lib/webauthn/signature_verifier.rb
spec/conformance/Gemfile.lock
spec/webauthn/credential_creation_options_spec.rb
spec/webauthn/signature_verifier_spec.rb
spec/webauthn_spec.rb
webauthn.gemspec

`verify_pss` is available since OpenSSL gem 2.1: https://github.com/ruby/openssl/pull/169
Per https://tools.ietf.org/html/rfc8230#section-2
- the same hash function for hashing and mask generation function is used
- the salt length must be the same as the hash function output
Prioritize PS256 over RS256 per https://tools.ietf.org/html/rfc8017#section-8:
> Although no attacks are known against RSASSA-PKCS1-v1_5, in the interest of increased robustness, RSASSA-PSS is REQUIRED in new applications. RSASSA-PKCS1-v1_5 is included only for compatibility with existing applications.
Refactored the tests a little to use RSpec's array matcherfor credential creation options.

Add support for RSA Probabilistic Signature Scheme with SHA256

---

README.md
lib/webauthn/authenticator_assertion_response.rb
lib/webauthn/fake_authenticator.rb
lib/webauthn/fake_client.rb
spec/conformance/server.rb
spec/webauthn/authenticator_assertion_response_spec.rb

This implements step 17 of [Verifying an Authentication Assertion](https://www.w3.org/TR/webauthn/#verifying-assertion). While working on the U2F migration I realized it'd be weird to lose the signature count verification by migrating to WebAuthn.
While working on this I realized the way we pass `allowed_credentials` doesn't really work nicely in the case you still need the stored credential for something after. This is being improved in the 2.0 API: https://github.com/cedarcode/webauthn-ruby/pull/194
Also related to https://github.com/cedarcode/webauthn-ruby/issues/200 although the conformance tool was already passing this test, only the Ruby error is `UserVerifiedVerificationError` instead of the expected `SignCountVerificationError` so that still needs looking into.

Add signature counter verification

---

lib/webauthn/authenticator_attestation_response.rb
lib/webauthn/configuration.rb
spec/webauthn/authenticator_attestation_response_spec.rb

Trying to implement #213. Looking for feedback on desired implementation. @bdewater @grzuy

feat: skip verifying attestation statement

---

lib/webauthn/fake_authenticator/authenticator_data.rb

… like it's real counterpart. This will help the U2fMigrator to have the same interface as a live U2F registered credential.

Expose FakeAuthenticator::AuthenticatorData#sign_count publically

---

README.md
docs/u2f_migration.md
lib/webauthn/u2f_migrator.rb
spec/support/seeds.rb
spec/webauthn/authenticator_assertion_response_spec.rb
spec/webauthn/u2f_migrator_spec.rb

Spent an afternoon hacking on this with @jdongelmans and we managed to make something work 😄Still need to figure out the last part on how to make credentials registered with U2F and WebAuthn play nicely with each other, but the rest of it is ready for review.
Closes https://github.com/cedarcode/webauthn-ruby/issues/92
cc @lgarron @sandergroen @brodock requesting your feedback since you have expressed interest on this subject here. If there's any implementation experience you can share, that'd be awesome 🙌

U2F migration guide

---

lib/webauthn/fake_authenticator.rb
lib/webauthn/fake_authenticator/attestation_object.rb
lib/webauthn/fake_client.rb

Closes #221 
I choose to keep track inside `FakeAuthenticator` to emulate what happens in real life a bit better. `FakeClient` should now be keeping a signature counter.

feat: increment sign count in fake authenticator

---

lib/webauthn/attestation_statement/fido_u2f.rb
lib/webauthn/attestation_statement/packed.rb
lib/webauthn/attestation_statement/tpm.rb
lib/webauthn/authenticator_data/attested_credential_data.rb
spec/webauthn/attestation_statement/packed_spec.rb
spec/webauthn/authenticator_attestation_response_spec.rb

This makes it easier to look them up in the metadata service

Format AAGUIDs properly

---

lib/webauthn/attestation_statement/android_safetynet.rb

[`add_cert`](https://www.openssl.org/docs/man1.1.1/man3/X509_STORE_add_cert.html) is for added trusted root certificates, the second argument to `verify` is for any untrusted intermediate or root certificate input

Properly verify SafetyNet certificates from input

---

README.md
lib/webauthn/configuration.rb
lib/webauthn/credential_creation_options.rb
lib/webauthn/credential_options.rb
lib/webauthn/credential_request_options.rb
spec/webauthn/credential_creation_options_spec.rb
spec/webauthn/credential_request_options_spec.rb

Add the ability to configure timeout in config. Defaults to 120s.
Closes #181

feat: configure timeout in config

---

lib/webauthn/encoder.rb
lib/webauthn/public_key_credential.rb
spec/conformance/server.rb
spec/webauthn/public_key_credential_spec.rb

* FIDO2 conformance tools
* @github/webauthn-json
addresses https://github.com/cedarcode/webauthn-ruby/pull/224#discussion_r313445260

feat: make PublicKeyCredential default encoding more compatible with external tools

---

README.md
lib/webauthn/authenticator_assertion_response.rb
lib/webauthn/public_key_credential.rb
spec/conformance/server.rb
spec/webauthn/authenticator_assertion_response_spec.rb

This is a breaking change, hence targeted for 2.0.
The reason to push the responsibility up to the application to find the right public_key for a given credential ID is that applications that want to do signature counter verification and updating (a "SHOULD" in the standard) need to do so anyway. It doesn't make much sense to have both the gem and the app find the right credential independently. This came up in https://github.com/cedarcode/webauthn-ruby/pull/215
The AuthenticatorAssertionResponse object doesn't need to know about the credential ID anymore either.

Changed allowed_credentials to just take one public_key

---

lib/webauthn/fake_client.rb

Refs:
https://www.w3.org/TR/webauthn-2/#iface-pkcredential
https://www.w3.org/TR/webauthn-2/#base64url-encoding

fix: make FakeClient follow WebAuthn spec by not padding base64url of id

---

README.md
lib/webauthn/authenticator_assertion_response.rb
spec/webauthn/authenticator_assertion_response_spec.rb

Helps in detecting cloned or malfunctioning authenticators: https://www.w3.org/TR/webauthn-2/#sctn-sign-counter
Applications can keep passing `0` if they wish not to do verify the counter as that'll always make the following return `true`:
https://github.com/cedarcode/webauthn-ruby/blob/95b403a4967bbbdf2606593061c2307aa4d27105/lib/webauthn/authenticator_assertion_response.rb#L48-L54

Make sign_count argument mandatory for verification

---

spec/webauthn/authenticator_attestation_response_spec.rb
spec/webauthn/public_key_credential/creation_options_spec.rb
spec/webauthn/public_key_credential/request_options_spec.rb

Replace `Encoding::ASCII_8BIT` with `Encoding::BINARY` to make code consistent and more intuitive

Use binary encoding alias

---

lib/webauthn.rb
lib/webauthn/public_key_credential.rb
spec/webauthn/public_key_credential/creation_options_spec.rb
spec/webauthn_spec.rb

Add new `WebAuthn.generate_user_id` method to generate user ids according to spec recommendation.
Closes #258

Add new method to generate user ids according to spec recommendation

---

lib/webauthn/fake_client.rb
spec/webauthn/authenticator_assertion_response_spec.rb
spec/webauthn/authenticator_attestation_response_spec.rb
spec/webauthn/credential_spec.rb
spec/webauthn/public_key_credential_spec.rb

Use `WebAuthn.configuration.encoding` (which defaults in `:base64url`) as default encoding

Set default encoding for FakeClient

---

README.md

docs: update README Usage

---

lib/webauthn/authenticator_response.rb
lib/webauthn/configuration.rb
spec/conformance/server.rb

Driven by need to pass FIDO2 conformance tools (v1.2.0) tests:
- GetAssertion Resp-3 P-4
- GetAssertion Resp-3 P-7
Closes #199

feat: add ability to optionally enable 'silent authentication'

---

lib/android_safetynet/attestation_response.rb
lib/webauthn/attestation_statement/android_safetynet.rb
spec/android_safetynet/attestation_response_spec.rb
spec/conformance/server.rb
spec/spec_helper.rb
spec/webauthn/attestation_statement/android_safetynet_spec.rb
spec/webauthn/authenticator_attestation_response_spec.rb
webauthn.gemspec

Pass MakeCredential Resp-B P-1 (closes #172) conformance test by avoiding the certificate chain verification on the conformance server.
Also closes #240 by correctly validating the timestamp on the attestation.

Pass remaining android-safetynet attestation conformance tests

---

lib/webauthn/metadata/statement.rb

This allows you to use a ActiveSupport::Cache instance in a Rails app without getting errors on writing the cache:
```ruby
WebAuthn.configure do |config|
config.cache_backend = ActiveSupport::Cache::FileStore.new(
Rails.root.join("tmp", "cache", "webauthn")
)
end
```

Lazy load X509::Certificates instead of during parsing/setting values on Metadata::Statement

---

lib/webauthn/authenticator_assertion_response.rb
lib/webauthn/public_key.rb
spec/webauthn/public_key_spec.rb

WebAuthn has some custom logic to account for backward compatibility on the deserialization of stored public keys in older formats. See [this comment](https://github.com/cedarcode/webauthn-ruby/blob/v2.0.0/lib/webauthn/authenticator_assertion_response.rb#L76).
Up until now, this logic is was not properly encapsulated so that it could be reused from other parts of the gem, or even to be used as a public API.
Motivated by https://github.com/cedarcode/webauthn-ruby/issues/222 and in collaboration with @padulafacundo  a new method is now exposed to be able to check that a stored public key abides by the expected formatting.
If `WebAuthn::PublicKey.deserialize(stored_public_key)` succeeds, then a user can be sure the key is valid.

Encapsulate WebAuthn::PublicKey behaviour

---

spec/conformance/conformance_patches.rb
spec/conformance/server.rb

There's only one valid manufacturing ID in conformance testing.
Fixes https://github.com/cedarcode/webauthn-ruby/pull/291#issuecomment-568765419

test: patch in TPM conformance test behaviour

---

lib/webauthn/attestation_statement.rb

Every call to `require` needs to scan `$LOAD_PATH`. By doing this only once and at boot, forking app server can also take advantage of copy-on-write.

Always require attestation format classes

---

lib/webauthn/attestation.rb
lib/webauthn/attestation_statement/android_key.rb
lib/webauthn/attestation_statement/android_safetynet.rb
lib/webauthn/attestation_statement/base.rb
lib/webauthn/attestation_statement/fido_u2f.rb
lib/webauthn/attestation_statement/none.rb
lib/webauthn/attestation_statement/packed.rb
lib/webauthn/attestation_statement/tpm.rb
lib/webauthn/authenticator_attestation_response.rb
lib/webauthn/authenticator_data.rb
spec/webauthn/authenticator_attestation_response_spec.rb

Split the `AuthenticatorAttestationResponse` into `AuthenticatorAttestationResponse` and `Attestation` in an attempt to provide easier maintainability and making it easier to reason about new features involving "attestation", by better encapsulating different concepts in different objects.

refactor: Attestation concept encapsulation

---

lib/webauthn/authenticator_data.rb
lib/webauthn/authenticator_data/attested_credential_data.rb
lib/webauthn/fake_client.rb
spec/webauthn/attestation_statement/fido_u2f_spec.rb
spec/webauthn/attestation_statement/packed_spec.rb
spec/webauthn/authenticator_attestation_response_spec.rb

feat: verify credential public key algorithm

---

README.md
lib/webauthn/attestation_statement/base.rb
lib/webauthn/attestation_statement/packed.rb
lib/webauthn/attestation_statement/tpm.rb
spec/webauthn/attestation_statement/packed_spec.rb
spec/webauthn/attestation_statement/tpm_spec.rb

It's being removed from WebAuthn level 2 as it was never implemented by browser vendors or authenticator manufacturers, see https://github.com/w3c/webauthn/issues/1410

Remove ECDAA

---

spec/spec_helper.rb
spec/webauthn/attestation_statement/android_key_spec.rb
spec/webauthn/attestation_statement/packed_spec.rb
spec/webauthn/attestation_statement/tpm_spec.rb

Don't try to test certificate invalidation so close to the timestamp
limit. Not worth it and unreliable.
Inspired by https://github.com/cedarcode/tpm-key_attestation/pull/10.

test: fix flaky tests

---

.travis.yml
script/ci/install-openssl
script/ci/install-ruby
spec/conformance/Gemfile.lock
webauthn.gemspec

`AttestationStatement::TPM#valid?` is blowing up when using libssl v1.0.2.
The error was inside [TPM Key Attestation](https://github.com/cedarcode/tpm-key_attestation) – see https://github.com/cedarcode/tpm-key_attestation/pull/5 – so we must update that dependency.
- https://github.com/cedarcode/tpm-key_attestation/pull/5
- https://github.com/cedarcode/tpm-key_attestation/pull/6
- https://github.com/cedarcode/openssl-signature_algorithm/pull/1

fix: AttestationStatement::TPM#valid? blowing up when using libssl 1.0.2

---

.rubocop.yml

When bundler installs gems to the vendor directory, rubocop by picks up their configuration and tries to lint these files as well, leading to false positives.
Ran into this while trying to run Rubocop for https://github.com/cedarcode/webauthn-ruby/pull/296 locally.

Rubocop: ignore vendor directory

---

lib/webauthn/fake_authenticator.rb
lib/webauthn/fake_authenticator/attestation_object.rb
lib/webauthn/fake_client.rb
lib/webauthn/public_key_credential.rb
spec/webauthn/public_key_credential_spec.rb

Add the possibility of accessing to the client and authenticator extensions outputs in the PublicKeyCredential's models, so that it can be manually validated by the user according to their expectations.
Extracted from WebAuthn spec in the sections [7.1 Registering a New Credential](https://www.w3.org/TR/webauthn-2/#sctn-registering-a-new-credential) (step 17) and [7.2 Verifying an Authentication Assertion](https://www.w3.org/TR/webauthn-2/#sctn-verifying-assertion) (step 18):
> Verify that the values of the client extension outputs in clientExtensionResults and the authenticator extension outputs in the extensions in authData are as expected, considering the client extension input values that were given in options.extensions and any specific policy of the Relying Party regarding …

feat: add API methods for providing received extension information

---

README.md

After merging #317, we should update the docs for specifying how to get the extensions.

docs: add documentation for extensions

---

lib/webauthn/attestation_object.rb
lib/webauthn/attestation_statement.rb
lib/webauthn/attestation_statement/base.rb
lib/webauthn/authenticator_assertion_response.rb
lib/webauthn/authenticator_attestation_response.rb
lib/webauthn/authenticator_data/attested_credential_data.rb
lib/webauthn/authenticator_response.rb
lib/webauthn/configuration.rb
lib/webauthn/credential.rb
lib/webauthn/fake_client.rb
lib/webauthn/public_key_credential.rb
lib/webauthn/public_key_credential/creation_options.rb
lib/webauthn/public_key_credential/options.rb
lib/webauthn/public_key_credential/request_options.rb
lib/webauthn/relying_party.rb
spec/conformance/conformance_cache_store.rb
spec/conformance/server.rb
spec/spec_helper.rb
spec/webauthn/authenticator_attestation_response_spec.rb
spec/webauthn/relying_party_spec.rb

Create a new `RelyingParty` class to allow the user of the gem to set up multiple instances (tries to solve https://github.com/cedarcode/webauthn-ruby/issues/285). 
This class also makes the registration/authentication ceremonies simpler.

Support multiple relying parties

---

.rubocop.yml
spec/spec_helper.rb
spec/webauthn/attestation_statement/android_key_spec.rb
spec/webauthn/attestation_statement/android_safetynet_spec.rb
spec/webauthn/attestation_statement/fido_u2f_spec.rb
spec/webauthn/attestation_statement/none_spec.rb
spec/webauthn/attestation_statement/packed_spec.rb
spec/webauthn/attestation_statement/tpm_spec.rb
spec/webauthn/authenticator_data_spec.rb
webauthn.gemspec

Enabling new cops, only Lint/DeprecatedOpenSSLConstant (https://github.com/rubocop-hq/rubocop/pull/7950) needed correcting.

Update Rubocop to 0.86

---

lib/webauthn/public_key_credential/entity.rb
spec/webauthn/public_key_credential/creation_options_spec.rb

Remove the the image URL field from public key credential creation options.
Removing it since [it was removed from the spec](https://github.com/w3c/webauthn/pull/1337).

refactor: remove `icon` from `user` in public key options

---

lib/cose/rsapkcs1_algorithm.rb
spec/conformance/Gemfile.lock
webauthn.gemspec

As a side-effect this will add support for `ES256K` credentials, because of https://github.com/cedarcode/openssl-signature_algorithm/commit/bc11db7ed4dedd7f4543bba332aa18d6dfab8b51 and https://github.com/cedarcode/cose-ruby/commit/d44bbcaa9a1996c3cdfd6d06a656d64f919dfcd6.

refactor: update cose & tpm-key_attestation runtime dependencies

---

lib/webauthn/fake_client.rb

Right now, the fake client is not easy to use to emulate a resident key. However, whether the registration is a resident key is not included in the attestation/assertion data, so we can just include it in the `get` response (which this PR does).

Allow specifying a user handle for `FakeClient` `get`.

---

spec/conformance/conformance_patches.rb

Some TPM conformance tests were failing due to obsolete patch

Remove obsolete patch

---

lib/webauthn/attestation_statement/none.rb
spec/webauthn/attestation_statement/none_spec.rb

Fix: validate acceptable attestation type inclusion when attestation statement is None

---

README.md
docs/advanced_configuration.md

This PR is a follow up of #296  to document the new instance based way of configuring and the corresponding API changes introduced in 3.0.0.alpha1
It was added as a separate section (taking the suggestions from the original PR) not to get in the middle of the highest percentage of the gem users that might not need to see this for now. Also, I added a disclaimer in the section I document how to use the new API.

Docs: document Instance based configuration approach

---

.github/workflows/git.yml

Fixup commits are OK in pull requests, but without a check like this one though, it's easy to forget to squash them away before merging to master.
See https://thoughtbot.com/blog/autosquashing-git-commits
Followed this guide: https://github.com/marketplace/actions/block-fixup-commit-merge

Add Github action to prevent merging of fixup commits

---

.github/workflows/build.yml

This PR adds Ruby 3.1 to the CI matrix.

Add Ruby 3.1 to CI

---

lib/webauthn/attestation_statement/tpm.rb
lib/webauthn/fake_authenticator.rb
lib/webauthn/fake_authenticator/authenticator_data.rb
spec/spec_helper.rb
spec/webauthn/attestation_statement/fido_u2f_spec.rb
spec/webauthn/attestation_statement/packed_spec.rb
spec/webauthn/attestation_statement/tpm_spec.rb
spec/webauthn/public_key_spec.rb
webauthn.gemspec

This is not enough for OpenSSL 3 compatibility as various dependencies still need fixing, but as far as I know, it should fix all incompatible code from the `webauthn-ruby` gem itself without breaking compatibility with the 2.2 version of the `openssl` gem.
Actual compatibility with OpenSSL 3 would require at least the following to be merged:
- https://github.com/cedarcode/tpm-key_attestation/pull/16
- https://github.com/cedarcode/openssl-signature_algorithm/pull/5
- https://github.com/cedarcode/cose-ruby/pull/61

Prepare for OpenSSL 3 compatibility

---

CHANGELOG.md

I think there is a typo in CHANGELOG.md. The version released a few days ago should be 2.5.2, not 2.5.1.
https://github.com/cedarcode/webauthn-ruby/releases/tag/v2.5.2
(and in fact, there are 2 entries with version number 2.5.1)

Fix version number typo in CHANGELOG.md

---

docs/advanced_configuration.md

Rename `rp_id` to `id` to match the supported arguments

Fix `advanced_configuration.md` relaying party

---

.github/workflows/build.yml
.rubocop.yml
CHANGELOG.md
lib/webauthn/attestation_object.rb
lib/webauthn/attestation_statement.rb
lib/webauthn/attestation_statement/base.rb
lib/webauthn/authenticator_assertion_response.rb
lib/webauthn/authenticator_attestation_response.rb
lib/webauthn/authenticator_data/attested_credential_data.rb
lib/webauthn/authenticator_response.rb
lib/webauthn/configuration.rb
lib/webauthn/credential.rb
lib/webauthn/fake_client.rb
lib/webauthn/public_key_credential.rb
lib/webauthn/public_key_credential/creation_options.rb
lib/webauthn/public_key_credential/options.rb
lib/webauthn/public_key_credential/request_options.rb
lib/webauthn/relying_party.rb
lib/webauthn/u2f_migrator.rb
lib/webauthn/version.rb
spec/conformance/conformance_cache_store.rb
spec/conformance/server.rb
spec/spec_helper.rb
spec/webauthn/authenticator_attestation_response_spec.rb
spec/webauthn/relying_party_spec.rb
webauthn.gemspec

This is a rebase of https://github.com/cedarcode/webauthn-ruby/pull/296 on top of the current master branch, addressing the concerns from https://github.com/cedarcode/webauthn-ruby/issues/367 that one would have to pick between either the OpenSSL 3.0 compatibility or support for multiple relying parties.
While I was here I bumped the minimum Ruby to 2.5 for a green build.

3.0.0.alpha2

---

README.md

With iOS 16 releasing today this is going to be searched for more often I expect. @brauliomartinezlm can you add the [passkey](https://github.com/topics/passkey)/[passkeys](https://github.com/topics/passkeys) topics to the repo?
The podcast [Security. Cryptography. Whatever: Passkeys feat. Adam Langley](https://securitycryptographywhatever.buzzsprout.com/1822302/11122508-passkeys-feat-adam-langley) has an explanation on how the term 'passkey' came to be, but that seemed overkill for the readme.

Mention passkeys, add Apple dev docs to readme

---

docs/advanced_configuration.md

The correct method for `RelyingParty` is `options_for_registration`, but it's `options_for_create` in the document. This PR fixes the typo

Update RelyingParty documentation

---

.github/workflows/build.yml
.github/workflows/git.yml
spec/spec_helper.rb

Also updates the checkout action to v3.
Getting tests to run green on Ruby 3.2 required an update to the `fake_certificate_chain_validation_time` method, such that it separated out positional and keyword arguments and only passed the keyword arguments to the wrapped method.  Ruby 3.2 is somewhat more strict on the distinction between positional and keyword arguments.
This runs green on my fork.

Adds Ruby 3.2 to the CI matrix

---

lib/webauthn/authenticator_data.rb
lib/webauthn/fake_authenticator/authenticator_data.rb
lib/webauthn/public_key_credential.rb
spec/webauthn/authenticator_data_spec.rb

Add ability to access the `backup_eligibility` and `backup_state` flags in the authenticator data. 
Introduces the methods `PublicKeyCredential#backup_eligible?` and `PublicKeyCredential#backed_up?` to access them.
Level 3 of the draft adds this flags to the Authenticator Data: https://w3c.github.io/webauthn/#sctn-credential-backup. Those flags can be used to get information about credential's backup eligibility and current backup state. With the introduction of multi-device FIDO credentials, this information can be useful for Relying Parties. According to the [documentation](https://w3c.github.io/webauthn/#sctn-credential-backup):
> The following is a non-exhaustive list of how [Relying Parties](https://w3c.github.io/webauthn/#relying-party) might use these …

Add support for credential backup flags

---

webauthn.gemspec

This stops us from blocking newer Ruby or OpenSSL gem releases, for any future incompatibilities application authors can pin their OpenSSL version if need be.
Ref https://github.com/cedarcode/webauthn-ruby/issues/382

Remove upper version constraint on OpenSSL

---

lib/webauthn/credential.rb

This is a leftover from the [initial implementation](https://github.com/cedarcode/webauthn-ruby/pull/296/commits/80a5b5c292a2efd3d3ac4a1509f9e63c8c71e462#diff-4d6918aac61f2bd300984bf57e0b22f57876919c5eb3df532cd808dc065fa685) of supporting multiple relying party configurations, when the `relying_party` keyword argument in this file called `RelyingParty.new` instead of [using the Configuration object](https://github.com/cedarcode/webauthn-ruby/pull/296/commits/51ef18068684e72a3aefd6896000ef657d1d5f6d).
Closes #388

Fix circular require warning

---

lib/webauthn/fake_client.rb
lib/webauthn/public_key_credential.rb
spec/webauthn/public_key_credential_with_assertion_spec.rb
spec/webauthn/public_key_credential_with_attestation_spec.rb

https://w3c.github.io/webauthn/#iface-pkcredential
Level 3 draft of WebAuthn adds an optional parameter `authenticatorAttachment` on `PublicKeyCredential` (and  `AuthenticatorAttestationResponse` and `AuthenticatorAssertionResponse` which inherits it, of course).
This field allows RP developers to detect whether the authentication was done using platform authenticator that always exists on that particular device, or cross-platform authenticator that only exists on that device temporarily.
In the latter case of using cross-platform authenticator, RP can prompt the user to register a platform authenticator so that the user won't lose the ability to sign in on that device.
> Note: If, as the result of a [registration](https://w3c.github.io/webauthn/#registration-ceremony) or [authentication …

Add support for optional authenticator_attachment in PublicKeyCredential

---

lib/webauthn/encoder.rb
webauthn.gemspec

This avoids a warning emitted by Ruby 3.3.0-preview2.
Fixes #401.
EDIT: inline the base64 implementation, and leave code comments that remind the reader about what they are seeing there.
Turn the base64 gem into a spec-supporting development dependency.

Add base64 as an inlined implementation

---

lib/webauthn/public_key_credential.rb
lib/webauthn/public_key_credential_with_attestation.rb
spec/webauthn/public_key_credential_with_assertion_spec.rb
spec/webauthn/public_key_credential_with_attestation_spec.rb

`WebAuthn::PublicKeyCredentialWithAttestation#verify` causes `NoMethodError` if `challenge` is `nil`. as below:
```ruby
undefined method `end_with?' for nil:NilClass
if !str.end_with?("=") && str.length % 4 != 0
^^^^^^^^^^
base64.rb:102:in `urlsafe_decode64'
```
Since `challenge` is assumed to refer to a value stored in temporary storage such as `session`, there may be cases where it does not exist by accident.
This change will make the error messages that occur when the above problem occurs more user-friendly and will help users of this library understand the errors.

Suppressing unexpected error with `WebAuthn::PublicKeyCredentialWithAttestation#verify`

---

lib/webauthn/authenticator_attestation_response.rb

Hi, first of all, thank you for creating this wonderful gem. This fix is ​​minor.
While reading the source code of this gem, I found a class that was probably unnecessary, so I opened this PR.
`AttestationTrustworthinessVerificationError` was used in the past, but I think it is no longer necessary due to the following PR.
https://github.com/cedarcode/webauthn-ruby/commit/72fa6fd894f75c07ddd42c1220e0da10d03e2b6e#diff-827ce4b0bc96a14830dfe8af8a60e263d595300ae9cd680719370147465c8db4L42
```bash
$ git grep attestation_trustworthiness => None
$ git grep AttestationTrustworthinessVerificationError => None
```
Therefore, I thought that I forgot to remove, but what do you think?

Remove unnecessary class `AttestationTrustworthinessVerificationError`

---

lib/webauthn/authenticator_attestation_response.rb
lib/webauthn/fake_client.rb
spec/webauthn/authenticator_attestation_response_spec.rb

Step 23 of the [`Registering a New Credential` section of the WebAuthn Level 2 spec](https://www.w3.org/TR/webauthn-2/#sctn-registering-a-new-credential) states:
> It is RECOMMENDED to also:
>
>Associate the [credentialId](https://www.w3.org/TR/webauthn-2/#credentialid) with the transport hints returned by calling credential.[response](https://www.w3.org/TR/webauthn-2/#dom-publickeycredential-response).[getTransports()](https://www.w3.org/TR/webauthn-2/#dom-authenticatorattestationresponse-gettransports). This value SHOULD NOT be modified before or after storing it. It is RECOMMENDED to use this value to populate the [transports](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialdescriptor-transports) of the [allowCredentials](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentia …

Add interface for accessing `transports`

---

spec/webauthn/attestation_statement/packed_spec.rb
spec/webauthn/attestation_statement/tpm_spec.rb

Fixes #417.
Some tests fail when using OpenSSL v3. The issue is that, for testing the `valid?` method for attestation statements, we set up a certificate to have an invalid version (version is 1 initially) and expect the attestation statement to not be valid. But when setting up the certificate we have to sign it which, in newer versions of OpenSSL, updates the version to a valid one (version changes to be 2), thus causing the expectation to not be met and therefore the spec to fail.
This PR fixes the issue by changing the version after the certificate has been signed.

Fix tests failing with OpenSSL v3

---

lib/webauthn/authenticator_attestation_response.rb
lib/webauthn/authenticator_response.rb
lib/webauthn/public_key_credential_with_attestation.rb
lib/webauthn/relying_party.rb
spec/webauthn/authenticator_attestation_response_spec.rb
spec/webauthn/relying_party_spec.rb

new iOS / macOS now support passkey auto upgrade.
it doesn't support neither UV nor UP, and both flags are false by default.
to accept such attestations, those changes are needed.

passkey auto-upgrade need to skip user presence & verification check

---

lib/webauthn/authenticator_attestation_response.rb
lib/webauthn/authenticator_response.rb
lib/webauthn/public_key_credential_with_attestation.rb
lib/webauthn/relying_party.rb
spec/webauthn/authenticator_attestation_response_spec.rb
spec/webauthn/public_key_credential_with_attestation_spec.rb
spec/webauthn/relying_party_spec.rb

After #432 was merged it was possible to call `AuthenticatorResponse#verify` with `user_presence` being `true` while having enabled `silent_authentication` for the Relying Party and the method would not verify user presence which would be confusing for users.
This PR changes this behavior so that the `user_presence` param, when passed, will always override the `silent_authentication` config.

Allow `user_presence` param in `AuthenticatorResponse#verify` to override `silent_authentication` config

---

lib/webauthn/authenticator_assertion_response.rb
lib/webauthn/public_key_credential_with_assertion.rb
lib/webauthn/relying_party.rb
spec/webauthn/authenticator_assertion_response_spec.rb
spec/webauthn/public_key_credential_with_assertion_spec.rb
spec/webauthn/relying_party_spec.rb

Similar to #432 but for assertions.
This is just for completeness: as we have a Relying Party scoped config for skipping `user_presence` in `silent_authentication` and a param for skipping it when calling `verify` for attestations, it should be possible to also skip the `user_presence` check for assertions with a param instead of only with the global config.

Allow to skip `user_presence` check for assertions

---

lib/webauthn/fake_authenticator.rb
lib/webauthn/fake_authenticator/attestation_object.rb
lib/webauthn/fake_authenticator/authenticator_data.rb

Fixes #276.
The gem already supports EdDSA credential keys after https://github.com/cedarcode/cose-ruby/issues/48. This PR just updates `FakeAuthenticator`, `FakeAuthenticator::AttestationObject` and `FakeAuthenticator::AuthenticatorData` in order for them to be used with these keys.

[FakeAuthenticator] Support EdDSA credential keys

---

.github/workflows/build.yml
lib/webauthn.rb
lib/webauthn/camelize.rb
lib/webauthn/camelize_helper.rb
lib/webauthn/public_key_credential/entity.rb
lib/webauthn/public_key_credential/options.rb
webauthn.gemspec

Avoids monkey patching Hash and removes a  dependency on an external gem. 
This is a simpler version of the rails' camelize and deep_transform_keys

Remove awrence dependency and test against 3.4 with frozen strings

---

.github/workflows/build.yml

This will allow us to have an better idea of what's making the CI fail at first sight in case it's rubocop what's failing.

Run rubocop just one time as a separate job

---

CHANGELOG.md
lib/webauthn/version.rb

This PR bumps the version of the gem to `v3.2.0` and updates the `CHANGELOG.md` with the changes that will be introduced on this version.

Prepare for `v3.2.0` release

---

lib/webauthn/json_serializer.rb
spec/webauthn/public_key_credential/creation_options_spec.rb
spec/webauthn/public_key_credential/request_options_spec.rb

Attempts to fix #441.
In Rails, `nil` responds to `as_json` therefore the attributes whose value is `nil` are added to the result of `as_json`, which may end up causing issues with some authenticators – as described in the associated issue.
This PR attempts to fix this by adding another condition to the if to skip if the value for the attribute is `nil`.

Fix JSON Serializer generating json with attributes with a null value

---

lib/webauthn/json_serializer.rb

Attempts to fix #444.
To fix this, this commit attempts to go back at the initial approach - before 0aab12406 – that first converts the object into a hash and then camel cases its keys, even though more iterations are performed on the object.

Fix `PublicKeyCredential::Options#.as_json` not camelCase'ing keys of attributes with hash or arrays as values 

---

CHANGELOG.md
lib/webauthn/version.rb

This PR bumps the version of the gem to `v3.2.2` and updates the `CHANGELOG.md` with the changes that will be introduced on this version.

Prepare for `v3.2.2` release

---

spec/webauthn/attestation_statement/tpm_spec.rb
webauthn.gemspec

Upgrading tpm-key-attestation after release https://github.com/cedarcode/tpm-key_attestation/tree/v0.13.0

Upgrade tpm-key_attestation dependency

---

.github/workflows/build.yml

`ubuntu-20` images are being deprecated:
https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/#ubuntu-20-image-is-closing-down
This PR updates the CI ro run on `ubuntu-24` which is the latest `ubuntu` image available.

Update CI to run on `ubuntu-24`

---

README.md
lib/webauthn/authenticator_response.rb
lib/webauthn/client_data.rb
lib/webauthn/configuration.rb
lib/webauthn/relying_party.rb
spec/webauthn/authenticator_attestation_response_spec.rb
spec/webauthn/relying_party_spec.rb

As described in the issue https://github.com/cedarcode/webauthn-ruby/issues/428
when building a Relying Party that is supposed to be used by iOS and Android native clients, we need to be able to specify multiple allowed origins per RP (https://developer.android.com/identity/sign-in/credential-manager#verify-origin)
This is yet not supported by this library though is also part of standard specification https://w3c.github.io/webauthn/#sctn-validating-origin
Current workaround is to fallback to creating multiple RP abstractions per expected client platform (Android, iOS, etc) and select one of them based on `User-Agent` header (for example). That is of course troublesome and can actually be avoided. 
This PR allows a relying party to specify either string for origin or array of strings like …

feat: allow multiple origins set per RelyingParty

---

CHANGELOG.md

Thanks for the recent update!
Would you mind checking the version number in CHANGELOG.md? It looks a bit different from the actual version.

docs: Fix tpm-key_attestation version number in CHANGELOG.md

---

spec/webauthn/relying_party_spec.rb

This PR replaces the use of `OpenStruct` in our tests with `Struct`, as `OpenStruct` will no longer be part of the standard gems in `Ruby 3.5`.
```sh
ostruct was loaded from the standard library, but will no longer be
part of the default gems starting from Ruby 3.5.0.
```

Use `Struct` instead of `OpenStruct`

---

CHANGELOG.md
lib/webauthn/version.rb

This PR bumps the version of the gem to `v3.4.1` and updates the `CHANGELOG.md` with the changes that will be introduced on this version.

Prepare for `v3.4.1` release

---

docs/advanced_configuration.md

I came across a few typos while reading the document on `Advanced Configuration`. Changes in the PR fix them.

docs: fix typos in the `Advanced Configuration`

---

.rubocop.yml

```sh
rubocop-rspec extension supports plugin, specify `plugins: rubocop-rspec` instead of `require: rubocop-rspec` in webauthn-ruby/.rubocop.yml.
For more information, see https://docs.rubocop.org/rubocop/plugin_migration_guide.html.
rubocop-rake extension supports plugin, specify `plugins: rubocop-rake` instead of `require: rubocop-rake` in webauthn-ruby/.rubocop.yml.
For more information, see https://docs.rubocop.org/rubocop/plugin_migration_guide.html.
```

Support `rubocop` plugin API

---

.github/actions/install-openssl/action.yml
.github/actions/install-ruby/action.yml
.github/workflows/build.yml

Similar to https://github.com/cedarcode/tpm-key_attestation/pull/49.
> We got a notification that `ubuntu-20` images are being deprecated:
> 
> https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/#ubuntu-20-image-is-closing-down
> 
> After upgrading to `ubuntu-22` or `ubuntu-24` a lot of tests started to break due to the Rubies on those images coming with OpenSSL version 3+. That means that, by upgrading, we wouldn't have any way of testing against OpenSSL 1.1.1w
> 
> We still want to test against OpenSSL `1.1.1w` despite it being EOL. 
This PR updates our CI to manually install OpenSSL and Ruby so that we can test against different OpenSSL versions, without having to rely on the OpenSSL version that comes with the OS' …

Test against different OpenSSL library versions
