cedarcode/webauthn-ruby

- lib/webauthn.rb
- lib/webauthn/authenticator_assertion_response.rb
- lib/webauthn/authenticator_attestation_response.rb
- lib/webauthn/authenticator_response.rb
- spec/spec_helper.rb
- spec/webauthn/authenticator_assertion_response_spec.rb
> feat: Assertion response validates user presence

- README.md
> docs: hint user on expected argument data format/encoding

- lib/webauthn.rb
- lib/webauthn/authenticator_response.rb
- lib/webauthn/utils.rb
This was only used in one place, the indirection didn't seem worth it.
> refactor: remove utils

- README.md
> security: provide safe channel for users to report sec issues

- README.md
- lib/webauthn/fake_authenticator.rb
- lib/webauthn/fake_authenticator/attestation_object.rb
- lib/webauthn/fake_authenticator/authenticator_data.rb
- lib/webauthn/fake_client.rb
- spec/spec_helper.rb
- spec/webauthn/authenticator_assertion_response_spec.rb
- spec/webauthn/authenticator_attestation_response_spec.rb
- spec/webauthn/authenticator_data_spec.rb
> Improve faking Client & Authenticator behavoir

- lib/webauthn/fake_authenticator/authenticator_data.rb
- spec/webauthn/attestation_statement/fido_u2f_spec.rb
> test: improve test coverage for fido-u2f attestation validation

- spec/webauthn/attestation_statement/android_key_spec.rb
> test: improve test coverage of android-key attestation validation

- lib/webauthn/attestation_statement/fido_u2f.rb
- spec/webauthn/attestation_statement/fido_u2f_spec.rb
Verification step 2 in https://www.w3.org/TR/webauthn/#fido-u2f-attestation
> feat: verify U2F attestation certificate curve

- README.md
> docs: document rp_id in verify method interface

- lib/cose/algorithm.rb
- lib/webauthn/attestation_statement/android_key.rb
- lib/webauthn/attestation_statement/fido_u2f.rb
- lib/webauthn/attestation_statement/packed.rb
- lib/webauthn/authenticator_assertion_response.rb
- lib/webauthn/fake_authenticator/authenticator_data.rb
- lib/webauthn/signature_verifier.rb
- spec/webauthn/attestation_statement/android_key_spec.rb
- spec/webauthn/attestation_statement/packed_spec.rb
- spec/webauthn/signature_verifier_spec.rb
> feat: support RS256 signatures

- webauthn.gemspec
Some people might search for the full name of WebAuthn, U2F or FIDO 2.0
> Expand gemspec description to cover more searchable terms

- lib/android_safetynet/attestation_response.rb
This is in part of preparing for https://github.com/cedarcode/webauthn-ruby/issues/160
but these fixes are good to go out by themselves.
> Couple of Safetynet refactors

- spec/conformance/server.rb
Started trying to fix #188 and ended up here.
I realized that all we need to store cross-request are registered credentials. Couldn't find a reason to store any of the other stuff. Might be missing something though.
Anyway...
Closes #188.
Makes progress for #174 ― Fails for that test group drop from 13 to 9.
> test(conformance): credential storage

- lib/webauthn/authenticator_data.rb
- lib/webauthn/fake_authenticator/authenticator_data.rb
- spec/webauthn/authenticator_data_spec.rb
> feat: verify authenticator data length

- lib/webauthn/credential_creation_options.rb
- lib/webauthn/credential_request_options.rb
- spec/conformance/server.rb
> feat: smarter Credential Options

- lib/webauthn/authenticator_assertion_response.rb
- lib/webauthn/authenticator_attestation_response.rb
- lib/webauthn/authenticator_response.rb
- spec/conformance/server.rb
- spec/webauthn/authenticator_assertion_response_spec.rb
- spec/webauthn/authenticator_attestation_response_spec.rb
> feat: provide conditional UV flag verification

- lib/cose/algorithm.rb
- lib/webauthn/configuration.rb
- lib/webauthn/credential_creation_options.rb
- lib/webauthn/signature_verifier.rb
- spec/conformance/server.rb
- spec/webauthn/credential_creation_options_spec.rb
- spec/webauthn/signature_verifier_spec.rb
Closes #169 
Closes #171 
Closes #187
> feat: ability to opt-in to RS1 credential algorithm

- README.md
> Fix broken link branch dependant for U2F migration guide

- README.md
This is very similar to what we are doing now.
> docs: start following Conventional Commits spec

- lib/webauthn.rb
- lib/webauthn/authenticator_assertion_response.rb
- lib/webauthn/configuration.rb
- lib/webauthn/encoder.rb
- lib/webauthn/fake_client.rb
- lib/webauthn/public_key_credential.rb
- spec/conformance/server.rb
- spec/webauthn/public_key_credential_spec.rb
Closes #87 
Implements part of the proposal in #194 
Pending:
> feat: PublicKeyCredential.from_create/get

- webauthn.gemspec
See https://fidoalliance.org/specifications/ :)
> Fix FIDO2 name in gem description

- lib/webauthn/authenticator_attestation_response.rb
- lib/webauthn/fake_authenticator.rb
- lib/webauthn/fake_authenticator/attestation_object.rb
- lib/webauthn/fake_client.rb
- spec/webauthn/authenticator_attestation_response_spec.rb
> feat: verify attestedCredentialData present for AttestationResponse

- lib/webauthn/authenticator_assertion_response.rb
- lib/webauthn/public_key_credential.rb
- spec/webauthn/public_key_credential_spec.rb
> feat: provide WebAuthn::PublicKeyCredential#user_handle

- lib/webauthn/fake_client.rb
> test: Fixed fake_client URL

- lib/webauthn/attestation_statement/android_safetynet.rb
- spec/webauthn/attestation_statement/android_safetynet_spec.rb
> test: improve test coverage of android-safetynet attestation validation

- README.md
> docs: warn users about discrepancies between README and latest release

- lib/webauthn/fake_client.rb
> fix: make FakeClient#get response include userHandle

- README.md
- lib/webauthn.rb
- lib/webauthn/authenticator_response.rb
- lib/webauthn/client_data.rb
- lib/webauthn/configuration.rb
- lib/webauthn/encoder.rb
- lib/webauthn/fake_client.rb
- lib/webauthn/public_key_credential.rb
- lib/webauthn/public_key_credential/creation_options.rb
- lib/webauthn/public_key_credential/options.rb
- lib/webauthn/public_key_credential/request_options.rb
- spec/webauthn/public_key_credential/creation_options_spec.rb
- spec/webauthn/public_key_credential/request_options_spec.rb
- spec/webauthn/public_key_credential_spec.rb
- spec/webauthn_spec.rb
> Centralize encoding configuration

- README.md
> docs: add API section to the README

- lib/tpm/constants.rb
- lib/webauthn/attestation_statement/tpm.rb
- spec/webauthn/attestation_statement/tpm_spec.rb
Cherry-picked from https://github.com/cedarcode/webauthn-ruby/pull/253 now https://github.com/cedarcode/webauthn-ruby/pull/282 has landed - details in the commit message.
> Validate TPM attestation certificate Subject Alternative Name presence

- lib/tpm/ek_certificate.rb
- lib/webauthn/attestation_statement/tpm.rb
- spec/tpm/ek_certificate_spec.rb
- spec/webauthn/attestation_statement/tpm_spec.rb
> refactor: encapsulate TPM::EKCertificate

- lib/webauthn/attestation_statement/base.rb
- spec/webauthn/attestation_statement/fido_u2f_spec.rb
- spec/webauthn/attestation_statement/packed_spec.rb
> Correctly verify attestation that contains a just a batch certificate that is present in the attestation root certificates
